version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket-app
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - DB_PATH=/app/data/tickets.db
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    container_name: ticket-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

