version: '3.8'

services:
  nginx-temp:
    image: nginx:alpine
    container_name: nginx-temp
    volumes:
      - ./nginx-temp.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
    networks:
      - network1
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email elbukaevzaur@gmail.com --agree-tos --no-eff-email -d wsw-abo-ticket.info -d www.wsw-abo-ticket.info
    depends_on:
      - nginx-temp
    networks:
      - network1

networks:
  network1:
    driver: bridge